# ACL — principio de menor privilegio (coherente con Reto 1/2: seguridad operativa)
user admin
topic read $SYS/#
topic readwrite #

user sensor
topic write casa/gas/#

user nodered
topic read casa/gas/#
