# Mosquitto 2.x — broker MQTT (Reto 2 flujo / Reto 3 despliegue)

sys_interval 5

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true

max_connections 50
max_inflight_messages 20
max_queued_messages 100
